plugins {
	id "net.neoforged.moddev" version "2.0.82" // https://projects.neoforged.net/neoforged/ModDevGradle
}

group = "agency.highlysuspect.i4"
version = "0.0.1"
base {
	archivesName = "i4-neoforge"
}

sourceSets {
	generated
	
	vanilla
	
	nf {
		compileClasspath += sourceSets.vanilla.compileClasspath
		runtimeClasspath += sourceSets.vanilla.runtimeClasspath
		//resources.srcDirs += [sourceSets.vanilla.resources]
		//resources.srcDirs += [sourceSets.generated.resources]
	}
	
	//sigh
//	main {
//		compileClasspath += sourceSets.nf.compileClasspath
//		runtimeClasspath += sourceSets.nf.runtimeClasspath
//		compileClasspath += sourceSets.vanilla.compileClasspath
//		runtimeClasspath += sourceSets.vanilla.runtimeClasspath
//	}
}

neoForge {
	version "21.1.169" // https://projects.neoforged.net/neoforged/neoforge
	
	addModdingDependenciesTo sourceSets.vanilla
	addModdingDependenciesTo sourceSets.nf
	
	runs {
		client {
			client()
		}
		server {
			server()
		}
	}
	
	mods {
		i4 {
			sourceSet sourceSets.generated
			sourceSet sourceSets.nf
			sourceSet sourceSets.vanilla
		}
	}
}

dependencies {
	nfImplementation sourceSets.vanilla.output
}

jar {
	from sourceSets.generated.output
	from sourceSets.nf.output
	from sourceSets.vanilla.output
}

processNfResources {
	inputs.property 'version', project.version
	filesMatching(["META-INF/neoforge.mods.toml"]) {
		expand version: project.version
	}
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
java.withSourcesJar()
java.sourceCompatibility = java.targetCompatibility = JavaVersion.VERSION_21
tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 21
}

tasks.register("dgen2", JavaExec) {
	group "dgen"
	
	classpath = sourceSets.vanilla.runtimeClasspath
	mainClass = "agency.highlysuspect.i4.dgen.DgenEntrypoint"
	args = [
		//arg 0: generated sources dir
		sourceSets.generated.getResources().srcDirs.iterator().next().toString(),
		//arg 1: my own classes dir (used for class discovery bullshit)
		sourceSets.vanilla.output.classesDirs.iterator().next().toString(),
	]
}