modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-3.0-or-later"
issueTrackerURL = "https://github.com/quat1024/i4/issues"
#logoFile = "rebindnarratoricon.png"

[[mods]]
modId = "i4"
version = "$version"
displayName = "i4"
description = "Data flows through everything"
authors = "quaternary"

#[[mixins]]
#config = "rebind_narrator.mixins.json"