import net.fabricmc.loom.task.AbstractRunTask

architectury {
	compileOnly()
	platformSetupLoomIde()
	fabric()
}

configurations {
	vanilla {
		canBeResolved = true
		canBeConsumed = false
	}
	shadowBundle {
		canBeResolved = true
		canBeConsumed = false
	}
	compileClasspath.extendsFrom vanilla
	runtimeClasspath.extendsFrom vanilla
	developmentFabric.extendsFrom vanilla
}

//sigh. what's the right way to get resources in dev
var shit = tasks.register("shit", Copy) {
	from "../vanilla/src/main/resources"
	from "../vanilla/src/generated/resources"
	into sourceSets.main.output.resourcesDir
}
tasks.withType(AbstractRunTask).configureEach {
	it.dependsOn shit
}

dependencies {
	modImplementation "net.fabricmc:fabric-loader:0.16.10"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.115.1+1.21.1"
	
	vanilla(project(path: ':vanilla', configuration: 'namedElements')) { transitive false }
	shadowBundle project(path: ':vanilla', configuration: 'transformProductionFabric')
	shadowBundle project(path: ':vanilla', configuration: 'allMyResources')
}

shadowJar {
	configurations = [project.configurations.shadowBundle]
	archiveClassifier = 'dev-shadow'
}

remapJar {
	inputFile.set shadowJar.archiveFile
}